# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Neoway
tagline:             'BI API Documentation'
description:         'Visit <a href="http://neoway.com.br" target="_blank">Neoway</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
